version: '3'
services:
  web:
    build:
      context: ./web/
    ports:
      - "3000:80"
     
  api:
    build: 
      context: ./server/
    ports:
      - "3333:3333"
    depends_on:
      - "db_migration"
    
  db_migration:
    build: 
      context: ./server/
    command: bash -c "sleep 10 && npm run knex:migrate && npm run knex:seed" 
    depends_on:
      - "db"
      
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
    - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ecoleta
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      
volumes:
  db_data: